version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db
  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:8080"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
