name: Build & Push Docker Images (CI)

on:
  push:
    branches: [ "main" ]

jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: tid0509
          password: dckr_pat_yXtoqMrSHqo67xZkjHRyKR6Vuns

      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: tid0509/backend:latest

      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          tags: tid0509/frontend:latest
